groups: []
resources:
- name: src
  type: git
  source:
    branch: master
    uri: https://github.com/govau/torque
- name: ops
  type: git
  source:
    branch: master
    paths:
    - torque/*
    private_key: ((ops-git-deploy-key.private_key))
    uri: git@github.com:AusDTO/ops.git
- name: 6am
  type: time
  source:
    start: 6:00 AM
    stop: 7:00 AM
    location: Australia/Sydney
- name: img
  type: docker-image
  source:
    email: ((DOCKER_HUB_EMAIL))
    username: ((DOCKER_HUB_USERNAME))
    password: ((DOCKER_HUB_PASSWORD))
    repository: govau/torque
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
jobs:
- name: publish
  serial: true
  plan:
    - do:
      - get: src
        trigger: true
      - put: img
        params:
          build: src
          tag_as_latest: "true"
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: run
  serial: true
  plan:
  - do:
    - get: img
      passed:
        - publish
    - get: src
    - get: ops
    - get: 6am
      trigger: true
    - task: run
      file: src/ci/run.yml
      params:
        CIRCLE_TOKEN: ((CIRCLE_TOKEN))
        ENV_JSON: ((ENV_JSON))
  on_failure:
    put: slack
    params:
      text: |
        :x: $BUILD_PIPELINE_NAME $BUILD_JOB_NAME FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        